
test:
  stage: test
  image:
    docker:latest
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker-compose run jokes_app_flask python tests.py
