image: docker:latest
services:
  - docker:dind
before_script:
  - apk add --no-cache docker-compose
stages:
  - test
  - deploy

test:
  stage: test
  variables:
    POSTGRES_USER: "jokes_app"
    POSTGRES_PASSWORD: "jokes_app"
    POSTGRES_DB: "jokes_app_test"
  script:
    - docker-compose build
    - docker-compose up -d postgres
#    - docker-compose up -d pg-docker
    - docker-compose run --rm jokes_app_flask python tests.py

deploy:
  stage: deploy
  script:
    - docker-compose run -d jokes_app_flask nginx