
test:
  stage: test
  image:
    docker:latest
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker-compose up -d postgres
#    - docker-compose up -d pg-docker
    - docker-compose run --rm jokes_app_flask python tests.py
