version: '3'

services:
  jokes_app_flask:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
    command: gunicorn -b :8080 wsgi:app
    ports:
      - "8080:8080"
    expose:
      - "8080"
