version: '3'

services:
  postgres:
    image: postgres:12.0-alpine
    container_name: "postgres"
    ports:
      - "5432:5432"
    networks:
      - 'jokes_net'
    volumes:
      - "$HOME/docker/volumes/postgres:/var/lib/postgresql/data"

  jokes_app_flask:
    container_name: jokes_app
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        TEST_DATABASE_URL: ${TEST_DATABASE_URL}
    command: sh -c "gunicorn -b :8090 wsgi:app"
    ports:
      - "8090:8090"
    links:
      - "postgres:postgres"
    networks:
      - 'jokes_net'
#    depends_on:
#      - "pg-docker"
#    expose:
#      - "8080"

#  nginx:
#      build: ./web
#      ports:
#        - 80:80
#      depends_on:
#        - "jokes_app_flask"

networks:
  jokes_net: